### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [WebDevJ/Movie_Haus_3#17]
better example for this:

``` js
function addMovie(req, res, next) {
  db.none(`INSERT INTO movies (imdbID, poster, title, year, rated, director, actors, plot)
    VALUES($1, $2, $3, $4, $5, $6, $7, $8)`,
    [req.body.imdbID, req.body.Poster, req.body.Title, req.body.Year, req.body.Rated, req.body.Director, req.body.Actors, req.body.Plot])
    .then(function (data) {
      res.rows = data;
      next();
    })
    .catch(function (error) {
      console.error(error);
    });
}
```

would be:

``` js
function addMovie(req, res, next) {
  db.one(`INSERT INTO movies (imdbID, poster, title, year, rated, director, actors, plot)
    VALUES($/imdbID/, $/Poster/, $/Title/, $/Year/, $/Rated/, $/Director/, $/Actors/, $/Plot/)
    RETURNING *`, req.body)
    .then(function (movie) {
      res.rows = movie; // always one object, if you use `RETURNING *`
      next();
    })
    .catch(function (error) {
      console.error(error);
    });
}
```

**Comment by LGOLIK** [comment]
Thank you so much!

Really appreciate the feedback.

On Sat, Mar 12, 2016 at 4:46 PM, Vitaly Tomilov notifications@github.com
wrote:

> better example for this:
> 
> function addMovie(req, res, next) {
>   db.none(`INSERT INTO movies (imdbID, poster, title, year, rated, director, actors, plot)    VALUES($1, $2, $3, $4, $5, $6, $7, $8)`,
>     [req.body.imdbID, req.body.Poster, req.body.Title, req.body.Year, req.body.Rated, req.body.Director, req.body.Actors, req.body.Plot])
>     .then(function (data) {
>       res.rows = data;
>       next();
>     })
>     .catch(function (error) {
>       console.error(error);
>     });
> }
> 
> would be:
> 
> function addMovie(req, res, next) {
>   db.none(`INSERT INTO movies (imdbID, poster, title, year, rated, director, actors, plot)    VALUES($/imdbID/, $/Poster/, $/Title/, $/Year/, $/Rated/, $/Director/, $/Actors/, $/Plot/)    RETURNING *`, req.body)
>     .then(function (movie) {
>       res.rows = movie; // always one object, if you use `RETURNING *`
>       next();
>     })
>     .catch(function (error) {
>       console.error(error);
>     });
> }
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WebDevJ/Movie_Haus_3/issues/17.

## 

Lauren
